server:
  port: ${PORT:8081}
app:
  security:
    api-key: ${APP_API_KEY:change-me-dev-key}
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/payment_demo}
    username: ${DB_USERNAME:ecommerce}
    password: ${DB_PASSWORD:ecommerce}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

payment:
  webhook:
    secret: ${PAYMENT_WEBHOOK_SECRET:demo-secret}
